<RoundedInput@TextInput>:
    font_size: self.height/5
    size_hint: 0.8 , 1
    background_color: (0.4, 0.6, 1, 0.1)
    background_normal: ''
    background_active: ''
    border: (1, 1, 1, 1)
    padding:(self.width * 0.1, self.height*0.3)
    canvas.before:
        Color:
            rgba: (1, 1, 1, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [40,]
        Color:
            rgba: (0.5, 0.5, 0.5, 1)